name: CI/CD Pipeline

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"] # Lệnh này giúp pipeline chạy tiếp sau khi merge

# Cấp quyền cho GitHub Actions được phép ghi đè lên GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job 1: CI (Chạy tự động để test code)
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kiểm tra Code
        run: echo "Pass hết các bài test! Code an toàn."

  # Job 2: CD (Chờ duyệt thủ công mới deploy)
  deploy:
    needs: build
    environment:
      name: production-pages # Tên môi trường đòi hỏi người duyệt (bạn đã setup lúc nãy)
      url: ${{ steps.deployment.outputs.page_url }}
    # ĐIỂM QUAN TRỌNG: Chỉ cho phép deploy nút bấm khi code đã gộp vào main
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './BaiTap7/public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4